import React from 'react';
import Head from "next/head";

const Layout = ({children }) => {
    return (
        <div>
            <Head>
                <title>PokeDex</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>



            <header className="bg-slate-900 py-10 mb-10">
                
                        <h1 className="text-6xl text-center text-amber-400">PokeDex</h1>
                    
            </header>


            <main className="container mx-auto">
                {children}
            </main>

        </div>
    );
};

export default Layout;